/*
    Kapitus × Snowflake Cortex Code Hands-On Lab
    Admin Pre-Lab: Environment Setup
    
    Run as: ACCOUNTADMIN
    This is run by the admin BEFORE the lab. Attendees do NOT run this.
    Kept as a reference asset in the repo.
*/

USE ROLE ACCOUNTADMIN;

--------------------------------------------------------------------
-- 1. Database & Warehouse
--------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS KAPITUS_TRAINING
    COMMENT = 'Cortex Code hands-on lab — Kapitus × Snowflake';

CREATE WAREHOUSE IF NOT EXISTS KAPITUS_TRAINING_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse for Kapitus training lab';

USE DATABASE KAPITUS_TRAINING;
USE WAREHOUSE KAPITUS_TRAINING_WH;

--------------------------------------------------------------------
-- 2. Shared Source Schema
--------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS SOURCE_DATA
    COMMENT = 'Shared source tables for all attendees';

--------------------------------------------------------------------
-- 3. Per-Attendee Schemas (one per username)
--------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS TRAINING_LUKE;
CREATE SCHEMA IF NOT EXISTS TRAINING_ALEX;
CREATE SCHEMA IF NOT EXISTS TRAINING_JORDAN;
CREATE SCHEMA IF NOT EXISTS TRAINING_MORGAN;
CREATE SCHEMA IF NOT EXISTS TRAINING_SAM;
CREATE SCHEMA IF NOT EXISTS TRAINING_TAYLOR;
CREATE SCHEMA IF NOT EXISTS TRAINING_CASEY;
CREATE SCHEMA IF NOT EXISTS TRAINING_JAMIE;

--------------------------------------------------------------------
-- 4. Workshop Role
--------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS KAPITUS_TRAINING_ROLE;

GRANT USAGE ON DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA KAPITUS_TRAINING.SOURCE_DATA TO ROLE KAPITUS_TRAINING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA KAPITUS_TRAINING.SOURCE_DATA TO ROLE KAPITUS_TRAINING_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;

GRANT USAGE ON WAREHOUSE KAPITUS_TRAINING_WH TO ROLE KAPITUS_TRAINING_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE KAPITUS_TRAINING_ROLE;

--------------------------------------------------------------------
-- 5. AI & ML Grants (future schemas covered)
--------------------------------------------------------------------
GRANT CREATE SEMANTIC VIEW ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE AGENT ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE MODEL ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT USAGE ON FUTURE MODELS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE STAGE ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE TASK ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE NOTEBOOK ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE STREAMLIT ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE DYNAMIC TABLE ON FUTURE SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;

--------------------------------------------------------------------
-- 6. Also grant on existing schemas (covers SOURCE_DATA + attendee schemas)
--------------------------------------------------------------------
GRANT CREATE SEMANTIC VIEW ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE AGENT ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE MODEL ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE TASK ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE NOTEBOOK ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE STREAMLIT ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;
GRANT CREATE DYNAMIC TABLE ON ALL SCHEMAS IN DATABASE KAPITUS_TRAINING TO ROLE KAPITUS_TRAINING_ROLE;

--------------------------------------------------------------------
-- 7. Assign Role to Attendees (replace with actual usernames)
--------------------------------------------------------------------
GRANT ROLE KAPITUS_TRAINING_ROLE TO USER LTURANSKI;
-- GRANT ROLE KAPITUS_TRAINING_ROLE TO USER <username>;
-- GRANT ROLE KAPITUS_TRAINING_ROLE TO USER <username>;
