/*
    Kapitus × Snowflake Cortex Code Hands-On Lab
    Step 3: Dynamic Table — Loan Analytics Mart
    
    IMPORTANT: This Dynamic Table is created in YOUR attendee schema.
    It READS from the shared SOURCE_DATA schema.
*/

USE DATABASE KAPITUS_TRAINING;
USE SCHEMA TRAINING_LUKE;  -- Replace with your schema (TRAINING_<USERNAME>)
USE WAREHOUSE KAPITUS_TRAINING_WH;

CREATE OR REPLACE DYNAMIC TABLE LOAN_ANALYTICS_MART
    TARGET_LAG = '1 hour'
    WAREHOUSE = KAPITUS_TRAINING_WH
    COMMENT = 'Denormalized loan analytics mart — refreshes hourly'
AS
SELECT
    la.APPLICATION_ID,
    la.BORROWER_ID,
    la.APPLICATION_DATE,
    la.LOAN_AMOUNT,
    la.LOAN_PURPOSE,
    la.LOAN_TERM_MONTHS,
    la.INTEREST_RATE,
    la.COLLATERAL_TYPE,
    la.COLLATERAL_VALUE,
    la.APPLICATION_STATUS,
    la.RISK_TIER,
    la.SUBMITTED_CHANNEL,
    la.IS_FRAUDULENT,

    b.BUSINESS_NAME,
    b.INDUSTRY,
    b.STATE,
    b.YEARS_IN_BUSINESS,
    b.ANNUAL_REVENUE,
    b.EMPLOYEE_COUNT,
    b.CREDIT_SCORE,
    b.EXISTING_DEBT,

    ld.DECISION_ID,
    ld.DECISION_DATE,
    ld.DECISION,
    ld.UNDERWRITER_ID,
    ld.DECISION_REASON,
    ld.APPROVED_AMOUNT,
    ld.PROCESSING_TIME_HRS,

    COALESCE(ph.TOTAL_PAYMENTS, 0)          AS TOTAL_PAYMENTS,
    COALESCE(ph.TOTAL_PAID, 0)              AS TOTAL_AMOUNT_PAID,
    COALESCE(ph.AVG_DAYS_LATE, 0)           AS AVG_DAYS_LATE,
    COALESCE(ph.LATE_PAYMENT_COUNT, 0)      AS LATE_PAYMENT_COUNT,
    COALESCE(ph.LATEST_BALANCE, 0)          AS REMAINING_BALANCE,

    ROUND(la.LOAN_AMOUNT / NULLIF(b.ANNUAL_REVENUE, 0), 4)  AS LOAN_TO_REVENUE_RATIO,
    ROUND(b.EXISTING_DEBT / NULLIF(b.ANNUAL_REVENUE, 0), 4) AS DEBT_TO_REVENUE_RATIO,
    ROUND(la.COLLATERAL_VALUE / NULLIF(la.LOAN_AMOUNT, 0), 4) AS COLLATERAL_COVERAGE_RATIO

FROM SOURCE_DATA.LOAN_APPLICATIONS la
LEFT JOIN SOURCE_DATA.BORROWERS b
    ON la.BORROWER_ID = b.BORROWER_ID
LEFT JOIN (
    SELECT *
    FROM SOURCE_DATA.LOAN_DECISIONS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY APPLICATION_ID ORDER BY DECISION_DATE DESC) = 1
) ld
    ON la.APPLICATION_ID = ld.APPLICATION_ID
LEFT JOIN (
    SELECT
        APPLICATION_ID,
        COUNT(*)                                    AS TOTAL_PAYMENTS,
        SUM(PAYMENT_AMOUNT)                        AS TOTAL_PAID,
        ROUND(AVG(DAYS_LATE), 1)                   AS AVG_DAYS_LATE,
        SUM(CASE WHEN DAYS_LATE > 0 THEN 1 ELSE 0 END) AS LATE_PAYMENT_COUNT,
        MAX_BY(REMAINING_BALANCE, PAYMENT_DATE)    AS LATEST_BALANCE
    FROM SOURCE_DATA.PAYMENT_HISTORY
    GROUP BY APPLICATION_ID
) ph
    ON la.APPLICATION_ID = ph.APPLICATION_ID;
